{"comments": {}, "bugs": {"1631603": {"comments": [{"count": 0, "raw_text": "I made some changes that involved deleting stuff from the geckoview api.txt file. I was told that running `./mach lint -l android-api-lint` would let me know of any problems. Instead I get this:\n\n```\nTraceback (most recent call last):\n  File \"/home/kats/zspace/gecko-misc/python/mozlint/mozlint/roller.py\", line 60, in _run_worker\n    res = func(paths, config, **lintargs) or []\n  File \"/home/kats/zspace/gecko-misc/python/mozlint/mozlint/types.py\", line 54, in __call__\n    return self._lint(paths, config, **lintargs)\n  File \"/home/kats/zspace/gecko-misc/python/mozlint/mozlint/types.py\", line 159, in _lint\n    return func(config, **lintargs)\n  File \"/home/kats/zspace/gecko-misc/tools/lint/android/lints.py\", line 88, in api_lint\n    issues = json.load(f)\n  File \"/usr/lib/python3.5/json/__init__.py\", line 268, in load\n    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)\n  File \"/usr/lib/python3.5/json/__init__.py\", line 319, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/lib/python3.5/json/decoder.py\", line 339, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/usr/lib/python3.5/json/decoder.py\", line 357, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\nA failure occurred in the android-api-lint linter.\n\u2716 1 problem (0 errors, 0 warnings, 1 failure)\n```", "text": "I made some changes that involved deleting stuff from the geckoview api.txt file. I was told that running `./mach lint -l android-api-lint` would let me know of any problems. Instead I get this:\n\n```\nTraceback (most recent call last):\n  File \"/home/kats/zspace/gecko-misc/python/mozlint/mozlint/roller.py\", line 60, in _run_worker\n    res = func(paths, config, **lintargs) or []\n  File \"/home/kats/zspace/gecko-misc/python/mozlint/mozlint/types.py\", line 54, in __call__\n    return self._lint(paths, config, **lintargs)\n  File \"/home/kats/zspace/gecko-misc/python/mozlint/mozlint/types.py\", line 159, in _lint\n    return func(config, **lintargs)\n  File \"/home/kats/zspace/gecko-misc/tools/lint/android/lints.py\", line 88, in api_lint\n    issues = json.load(f)\n  File \"/usr/lib/python3.5/json/__init__.py\", line 268, in load\n    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)\n  File \"/usr/lib/python3.5/json/__init__.py\", line 319, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/lib/python3.5/json/decoder.py\", line 339, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/usr/lib/python3.5/json/decoder.py\", line 357, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\nA failure occurred in the android-api-lint linter.\n\u2716 1 problem (0 errors, 0 warnings, 1 failure)\n```", "time": "2020-04-20T21:04:35Z", "creation_time": "2020-04-20T21:04:35Z", "is_private": false, "creator": "kats@bugmash.staktrace.com", "attachment_id": null, "author": "kats@bugmash.staktrace.com", "tags": [], "bug_id": 1631603, "id": 14767630}, {"creation_time": "2020-04-21T13:47:05Z", "text": "As far as I can tell this is trying to read an `apilint-result.json` file from my objdir. There's only one such file, and it's empty. So attempting to `json.load` it produces an error.", "author": "kats@bugmash.staktrace.com", "tags": [], "attachment_id": null, "count": 1, "is_private": false, "raw_text": "As far as I can tell this is trying to read an `apilint-result.json` file from my objdir. There's only one such file, and it's empty. So attempting to `json.load` it produces an error.", "time": "2020-04-21T13:47:05Z", "creator": "kats@bugmash.staktrace.com", "id": 14769013, "bug_id": 1631603}, {"author": "kats@bugmash.staktrace.com", "tags": [], "creator": "kats@bugmash.staktrace.com", "attachment_id": null, "id": 14769018, "bug_id": 1631603, "count": 2, "is_private": false, "raw_text": "And the error is showing up on try pushes, too: https://treeherder.mozilla.org/#/jobs?repo=try&group_state=expanded&revision=78e4e7bebf8d24f45edf35b33d1a84dd2becaeaa\n\nThe apilint-result.json artifact on the lint job has this:\n```\n{\n  \"reason\": \"file-missing-on-worker\",\n  \"message\": \"Artifact \\\"public/android/geckoview/apilint-result.json\\\" not found at \\\"/builds/worker/checkouts/gecko/obj-firefox/gradle/build/mobile/android/geckoview/intermediates/classes/withGeckoBinaries/debug/apilint-result.json\\\"\"\n}\n```", "time": "2020-04-21T13:49:54Z", "text": "And the error is showing up on try pushes, too: https://treeherder.mozilla.org/#/jobs?repo=try&group_state=expanded&revision=78e4e7bebf8d24f45edf35b33d1a84dd2becaeaa\n\nThe apilint-result.json artifact on the lint job has this:\n```\n{\n  \"reason\": \"file-missing-on-worker\",\n  \"message\": \"Artifact \\\"public/android/geckoview/apilint-result.json\\\" not found at \\\"/builds/worker/checkouts/gecko/obj-firefox/gradle/build/mobile/android/geckoview/intermediates/classes/withGeckoBinaries/debug/apilint-result.json\\\"\"\n}\n```", "creation_time": "2020-04-21T13:49:54Z"}, {"attachment_id": null, "author": "ahal@mozilla.com", "tags": [], "text": "Hey Nick, any idea why this file might be empty/missing?", "creation_time": "2020-04-21T14:35:47Z", "bug_id": 1631603, "id": 14769115, "creator": "ahal@mozilla.com", "raw_text": "Hey Nick, any idea why this file might be empty/missing?", "time": "2020-04-21T14:35:47Z", "is_private": false, "count": 3}, {"bug_id": 1631603, "id": 14769282, "creator": "kats@bugmash.staktrace.com", "time": "2020-04-21T14:45:42Z", "raw_text": "Subsequent try push with slightly modified code (fixed the dangling `import` statements in java code, etc.) now seem to be killing gradle: https://treeherder.mozilla.org/#/jobs?repo=try&group_state=expanded&revision=7ed7bc72c4c0bcc31ab60ddba291ba602a85afc1", "is_private": false, "count": 4, "attachment_id": null, "tags": [], "author": "kats@bugmash.staktrace.com", "creation_time": "2020-04-21T14:45:42Z", "text": "Subsequent try push with slightly modified code (fixed the dangling `import` statements in java code, etc.) now seem to be killing gradle: https://treeherder.mozilla.org/#/jobs?repo=try&group_state=expanded&revision=7ed7bc72c4c0bcc31ab60ddba291ba602a85afc1"}, {"raw_text": "I ran the lint command with `--verbose` which emitted a gradle command it was running under the hood. Running that manually pointed to an error in my changes to api.txt. Fixing that (and subsequently bumping the API version in a changelog.md file) fixed my linting errors.", "text": "I ran the lint command with `--verbose` which emitted a gradle command it was running under the hood. Running that manually pointed to an error in my changes to api.txt. Fixing that (and subsequently bumping the API version in a changelog.md file) fixed my linting errors.", "creation_time": "2020-04-21T15:28:08Z", "time": "2020-04-21T15:28:08Z", "is_private": false, "count": 5, "bug_id": 1631603, "id": 14769359, "creator": "kats@bugmash.staktrace.com", "attachment_id": null, "author": "kats@bugmash.staktrace.com", "tags": []}, {"raw_text": "Apilint issue https://github.com/mozilla-mobile/gradle-apilint/issues/77", "text": "Apilint issue https://github.com/mozilla-mobile/gradle-apilint/issues/77", "time": "2020-04-21T15:30:03Z", "creation_time": "2020-04-21T15:30:03Z", "is_private": false, "count": 6, "bug_id": 1631603, "id": 14769360, "creator": "agi@sferro.dev", "attachment_id": null, "author": "agi@sferro.dev", "tags": []}, {"attachment_id": 9143123, "creator": "agi@sferro.dev", "tags": [], "author": "agi@sferro.dev", "bug_id": 1631603, "id": 14776643, "count": 7, "creation_time": "2020-04-24T16:22:41Z", "text": "Created attachment 9143123\nBug 1631603 - Update apilint to 0.2.7.\n\nThis version includes the following commits:\n\nd89245f Update com.gradle.plugin-publish to 0.11.0.\n17bc5ea Closes #77: Don't fail when the map index is out of range.", "time": "2020-04-24T16:22:41Z", "raw_text": "This version includes the following commits:\n\nd89245f Update com.gradle.plugin-publish to 0.11.0.\n17bc5ea Closes #77: Don't fail when the map index is out of range.", "is_private": false}, {"count": 8, "is_private": false, "creation_time": "2020-04-27T15:57:23Z", "time": "2020-04-27T15:57:23Z", "text": "Pushed by asferro@mozilla.com:\nhttps://hg.mozilla.org/integration/autoland/rev/fcb4c961bba7\nUpdate apilint to 0.2.7. r=snorp", "raw_text": "Pushed by asferro@mozilla.com:\nhttps://hg.mozilla.org/integration/autoland/rev/fcb4c961bba7\nUpdate apilint to 0.2.7. r=snorp", "tags": [], "author": "pulsebot@bots.tld", "attachment_id": null, "creator": "pulsebot@bots.tld", "id": 14781920, "bug_id": 1631603}, {"attachment_id": null, "creator": "shindli@mozilla.com", "tags": ["bugherder"], "author": "shindli@mozilla.com", "bug_id": 1631603, "id": 14782690, "count": 9, "time": "2020-04-27T21:53:09Z", "creation_time": "2020-04-27T21:53:09Z", "text": "https://hg.mozilla.org/mozilla-central/rev/fcb4c961bba7", "raw_text": "https://hg.mozilla.org/mozilla-central/rev/fcb4c961bba7", "is_private": false}]}}}