{"bugs": {"678523": {"comments": [{"creator": "mbrandt@mozilla.com", "author": "mbrandt@mozilla.com", "bug_id": 678523, "tags": [], "count": 0, "is_private": false, "id": 5650161, "text": "These are new, I've seen a few of these tracebacks trickle in recently but have been unable to reproduce the error. I don't believe this is a new trend where users are being prevented from signing up for the newsletter but this might be worth exploring a bit. \n\nI realize we're going to sunset the site soon :)\n\n========================================\n\nTraceback (most recent call last):\n\n File \"/data/www/markup.mozilla.org/markup/ffdemo/vendor/src/django/django/core/handlers/base.py\", line 100, in get_response\n   response = callback(request, *callback_args, **callback_kwargs)\n\n File \"/data/www/markup.mozilla.org/markup/ffdemo/responsys/views.py\", line 35, in subscribe\n   data['country'])\n\n File \"/data/www/markup.mozilla.org/markup/ffdemo/responsys/responsys.py\", line 47, in subscribe\n   raise Exception('Newsletter subscription failed: %s' % ce)\n\nException: Newsletter subscription failed: (60, 'Peer certificate cannot be authenticated with known CA certificates')", "time": "2011-08-12T16:19:53Z", "attachment_id": null, "raw_text": "These are new, I've seen a few of these tracebacks trickle in recently but have been unable to reproduce the error. I don't believe this is a new trend where users are being prevented from signing up for the newsletter but this might be worth exploring a bit. \n\nI realize we're going to sunset the site soon :)\n\n========================================\n\nTraceback (most recent call last):\n\n File \"/data/www/markup.mozilla.org/markup/ffdemo/vendor/src/django/django/core/handlers/base.py\", line 100, in get_response\n   response = callback(request, *callback_args, **callback_kwargs)\n\n File \"/data/www/markup.mozilla.org/markup/ffdemo/responsys/views.py\", line 35, in subscribe\n   data['country'])\n\n File \"/data/www/markup.mozilla.org/markup/ffdemo/responsys/responsys.py\", line 47, in subscribe\n   raise Exception('Newsletter subscription failed: %s' % ce)\n\nException: Newsletter subscription failed: (60, 'Peer certificate cannot be authenticated with known CA certificates')", "creation_time": "2011-08-12T16:19:53Z"}]}}, "comments": {}}