{"comments": {}, "bugs": {"646655": {"comments": [{"author": "brandon@hackmill.com", "is_private": false, "id": 5381665, "creation_time": "2011-03-30T22:29:43Z", "tags": [], "attachment_id": null, "bug_id": 646655, "time": "2011-03-30T22:29:43Z", "count": 0, "raw_text": "To reproduce:\n1. go to https://www.irs.gov\n2. Ctrl-U to view source\n\n(going directly to view-source:https://www.irs.gov produces only a subset of the bug)\n\nNote that the error message says \"You have asked Minefield to connect\nsecurely to , but we can't confirm...\"  (missing the domain name) and the Add Exception button is disabled.", "creator": "brandon@hackmill.com", "text": "To reproduce:\n1. go to https://www.irs.gov\n2. Ctrl-U to view source\n\n(going directly to view-source:https://www.irs.gov produces only a subset of the bug)\n\nNote that the error message says \"You have asked Minefield to connect\nsecurely to , but we can't confirm...\"  (missing the domain name) and the Add Exception button is disabled."}, {"id": 5382064, "is_private": false, "author": "bzbarsky@mit.edu", "time": "2011-03-31T01:09:05Z", "count": 1, "bug_id": 646655, "text": "Right, because a view-source: URI has no hostname, so there's no hostname to show and nothing to add an exception for.\n\nIsn't the real issue here that view-source is enabled on that error page at all?  There are bugs on that...", "creation_time": "2011-03-31T01:09:05Z", "tags": [], "attachment_id": null, "raw_text": "Right, because a view-source: URI has no hostname, so there's no hostname to show and nothing to add an exception for.\n\nIsn't the real issue here that view-source is enabled on that error page at all?  There are bugs on that...", "creator": "bzbarsky@mit.edu"}, {"raw_text": "", "creator": "bugzilla@mversen.de", "creation_time": "2011-03-31T23:55:47Z", "tags": [], "attachment_id": null, "text": "*** Bug 647016 has been marked as a duplicate of this bug. ***", "bug_id": 646655, "author": "bugzilla@mversen.de", "time": "2011-03-31T23:55:47Z", "count": 2, "is_private": false, "id": 5385099}, {"id": 5385220, "is_private": false, "count": 3, "author": "j@marguerie.org", "time": "2011-04-01T00:35:49Z", "bug_id": 646655, "text": "(In reply to comment #1)\n> Right, because a view-source: URI has no hostname, so there's no hostname to\n> show and nothing to add an exception for.\n> \n> Isn't the real issue here that view-source is enabled on that error page at\n> all?  There are bugs on that...\n\nClearly not viewing the content is a problem.\nHowever, as the page can give credentials in the URL, firefox must tell the user if the certificate is broken and ask him what to do.", "attachment_id": null, "creation_time": "2011-04-01T00:35:49Z", "tags": [], "creator": "j@marguerie.org", "raw_text": "(In reply to comment #1)\n> Right, because a view-source: URI has no hostname, so there's no hostname to\n> show and nothing to add an exception for.\n> \n> Isn't the real issue here that view-source is enabled on that error page at\n> all?  There are bugs on that...\n\nClearly not viewing the content is a problem.\nHowever, as the page can give credentials in the URL, firefox must tell the user if the certificate is broken and ask him what to do."}, {"bug_id": 646655, "attachment_id": null, "creation_time": "2011-04-01T12:00:29Z", "tags": [], "id": 5386061, "author": "bzbarsky@mit.edu", "is_private": false, "text": "I'm not sure I follow comment 3.", "creator": "bzbarsky@mit.edu", "raw_text": "I'm not sure I follow comment 3.", "count": 4, "time": "2011-04-01T12:00:29Z"}, {"count": 5, "time": "2012-02-23T07:12:49Z", "author": "bugzilla@mversen.de", "is_private": false, "id": 6085723, "creator": "bugzilla@mversen.de", "raw_text": "", "attachment_id": null, "creation_time": "2012-02-23T07:12:49Z", "tags": [], "text": "*** Bug 729610 has been marked as a duplicate of this bug. ***", "bug_id": 646655}, {"count": 6, "time": "2012-08-22T03:03:25Z", "text": "I reported bug 729610 which was marked as a duplicate of this one. I filed the bug BECAUSE I was unable to view the source of the error page itself. I wanted to view the source of the error page, but the source was not displayed.", "creator": "andrew@joako.net", "raw_text": "I reported bug 729610 which was marked as a duplicate of this one. I filed the bug BECAUSE I was unable to view the source of the error page itself. I wanted to view the source of the error page, but the source was not displayed.", "id": 6573148, "author": "andrew@joako.net", "is_private": false, "bug_id": 646655, "attachment_id": null, "creation_time": "2012-08-22T03:03:25Z", "tags": []}, {"is_private": false, "author": "deletesoftware+moz@yandex.ru", "id": 8482247, "tags": [], "creation_time": "2014-03-03T09:25:44Z", "attachment_id": null, "bug_id": 646655, "time": "2014-03-03T09:25:44Z", "count": 7, "raw_text": "", "creator": "deletesoftware+moz@yandex.ru", "text": "*** Bug 976564 has been marked as a duplicate of this bug. ***"}, {"text": "This is a front-end bug. \"View source\" shouldn't be available for connection error pages (as per comment 1).", "raw_text": "This is a front-end bug. \"View source\" shouldn't be available for connection error pages (as per comment 1).", "creator": "dkeeler@mozilla.com", "time": "2016-05-20T17:57:20Z", "count": 8, "bug_id": 646655, "creation_time": "2016-05-20T17:57:20Z", "tags": [], "attachment_id": null, "id": 11426204, "author": "dkeeler@mozilla.com", "is_private": false}, {"bug_id": 646655, "text": "Still an issue in Quantum (68.0.1) \n\nview-source:https://expired.badssl.com/ -> Advanced", "tags": [], "creation_time": "2019-08-02T20:58:00Z", "attachment_id": null, "raw_text": "Still an issue in Quantum (68.0.1) \n\nview-source:https://expired.badssl.com/ -> Advanced", "creator": "13hurdw@gmail.com", "id": 14277264, "is_private": false, "time": "2019-08-02T20:58:00Z", "author": "13hurdw@gmail.com", "count": 9}]}}}