{"comments": {}, "bugs": {"1630048": {"comments": [{"bug_id": 1630048, "attachment_id": null, "is_private": false, "text": "This bug is for a permafailure in visual metrics tasks for geckoview tests (jianshu, web.de):\n```\n[task 2020-04-08T15:14:07.144Z] 2020-04-08T15:14:07.144847Z Extracted browsertime results  path=PosixPath('/builds/worker/fetches/browsertime-results.tgz')\n[task 2020-04-08T15:14:07.145Z] 2020-04-08T15:14:07.145132Z Loaded JSON from file          path=PosixPath('/builds/worker/fetches/browsertime-results/jobs.json') read_json={'jobs': [{'test_name': '360-cn-cold-live', 'browsertime_json_path': 'browsertime-results/360-cn-cold-live/browsertime.json'}], 'application': {'version': '80.0.3987.162', 'name': 'chrome-m'}}\n[task 2020-04-08T15:14:07.146Z] 2020-04-08T15:14:07.145561Z Could not read JSON file       path=PosixPath('/builds/worker/fetches/browsertime-results/360-cn-cold-live/browsertime.json')\n[task 2020-04-08T15:14:07.146Z] Traceback (most recent call last):\n[task 2020-04-08T15:14:07.146Z]   File \"/builds/worker/bin/run-visual-metrics.py\", line 158, in read_json\n[task 2020-04-08T15:14:07.146Z]     data = json.load(f)\n[task 2020-04-08T15:14:07.146Z]   File \"/usr/lib/python3.5/json/__init__.py\", line 265, in load\n[task 2020-04-08T15:14:07.146Z]     return loads(fp.read(),\n[task 2020-04-08T15:14:07.147Z]   File \"/usr/lib/python3.5/encodings/ascii.py\", line 26, in decode\n[task 2020-04-08T15:14:07.147Z]     return codecs.ascii_decode(input, self.errors)[0]\n[task 2020-04-08T15:14:07.147Z] UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 17365: ordinal not in range(128)\n```", "raw_text": "This bug is for a permafailure in visual metrics tasks for geckoview tests (jianshu, web.de):\n```\n[task 2020-04-08T15:14:07.144Z] 2020-04-08T15:14:07.144847Z Extracted browsertime results  path=PosixPath('/builds/worker/fetches/browsertime-results.tgz')\n[task 2020-04-08T15:14:07.145Z] 2020-04-08T15:14:07.145132Z Loaded JSON from file          path=PosixPath('/builds/worker/fetches/browsertime-results/jobs.json') read_json={'jobs': [{'test_name': '360-cn-cold-live', 'browsertime_json_path': 'browsertime-results/360-cn-cold-live/browsertime.json'}], 'application': {'version': '80.0.3987.162', 'name': 'chrome-m'}}\n[task 2020-04-08T15:14:07.146Z] 2020-04-08T15:14:07.145561Z Could not read JSON file       path=PosixPath('/builds/worker/fetches/browsertime-results/360-cn-cold-live/browsertime.json')\n[task 2020-04-08T15:14:07.146Z] Traceback (most recent call last):\n[task 2020-04-08T15:14:07.146Z]   File \"/builds/worker/bin/run-visual-metrics.py\", line 158, in read_json\n[task 2020-04-08T15:14:07.146Z]     data = json.load(f)\n[task 2020-04-08T15:14:07.146Z]   File \"/usr/lib/python3.5/json/__init__.py\", line 265, in load\n[task 2020-04-08T15:14:07.146Z]     return loads(fp.read(),\n[task 2020-04-08T15:14:07.147Z]   File \"/usr/lib/python3.5/encodings/ascii.py\", line 26, in decode\n[task 2020-04-08T15:14:07.147Z]     return codecs.ascii_decode(input, self.errors)[0]\n[task 2020-04-08T15:14:07.147Z] UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 17365: ordinal not in range(128)\n```", "id": 14755289, "author": "gmierz2@outlook.com", "tags": [], "count": 0, "time": "2020-04-14T20:39:58Z", "creation_time": "2020-04-14T20:39:58Z", "creator": "gmierz2@outlook.com"}, {"raw_text": "This patch fixes a failure with encodings when opening JSONs. It changes the file opening portion to ignore these types of errors - they are occuring because of the different language being used. We have no need for this data so we can safely ignore them. One other change that is being done here is adding additional error logging because it was possible to lose an error stack trace.", "text": "Created attachment 9140574\nBug 1630048 - Fix visual metrics encoding failures. r?#perftest\n\nThis patch fixes a failure with encodings when opening JSONs. It changes the file opening portion to ignore these types of errors - they are occuring because of the different language being used. We have no need for this data so we can safely ignore them. One other change that is being done here is adding additional error logging because it was possible to lose an error stack trace.", "is_private": false, "author": "gmierz2@outlook.com", "id": 14755309, "bug_id": 1630048, "attachment_id": 9140574, "creator": "gmierz2@outlook.com", "creation_time": "2020-04-14T20:50:52Z", "count": 1, "tags": [], "time": "2020-04-14T20:50:52Z"}, {"is_private": false, "raw_text": "Pushed by gmierz2@outlook.com:\nhttps://hg.mozilla.org/integration/autoland/rev/d41099e117db\nFix visual metrics encoding failures. r=perftest-reviewers,Bebe", "text": "Pushed by gmierz2@outlook.com:\nhttps://hg.mozilla.org/integration/autoland/rev/d41099e117db\nFix visual metrics encoding failures. r=perftest-reviewers,Bebe", "author": "pulsebot@bots.tld", "id": 14773805, "bug_id": 1630048, "attachment_id": null, "creation_time": "2020-04-23T12:57:52Z", "creator": "pulsebot@bots.tld", "tags": [], "count": 2, "time": "2020-04-23T12:57:52Z"}, {"creator": "cbrindusan@mozilla.com", "creation_time": "2020-04-23T21:46:22Z", "author": "cbrindusan@mozilla.com", "id": 14775028, "raw_text": "https://hg.mozilla.org/mozilla-central/rev/d41099e117db", "text": "https://hg.mozilla.org/mozilla-central/rev/d41099e117db", "is_private": false, "time": "2020-04-23T21:46:22Z", "attachment_id": null, "bug_id": 1630048, "count": 3, "tags": ["bugherder"]}]}}}