{"comments": {}, "bugs": {"693494": {"comments": [{"text": "So, when I forget to connect my SSH tunnels and, thus, cannot proxy out I get a generic grey error bar about unable to connect with Sync.  When this happens, no logs are created at all, however once I *do* connect (either by disabling my proxy or connecting the SSH tunnels) lines like the following show up in the logs after a successful Sync.  So...that's buffering somewhere which might be a bad thing (how much buffer is allocated to junk like that?) and why isn't it logging *when* it's happening?\n\nExample log lines:\n1318269622886   Sync.Service       INFO   Starting sync at 2011-10-10 11:00:22\n1318269622898   Sync.SyncScheduler DEBUG    Clearing sync triggers.\n1318269622899   Sync.Service       INFO   In sync().\n1318269623231   Sync.Service       DEBUG  Exception: NS_ERROR_PROXY_CONNECTION_REFUSED JS Stack trace: Res_get()@resource.js:473 < _fetchInfo(...)@service.js:661 < ()@service.js:1451 < WrappedNotify()@util.js:164 < WrappedLock()@util.js:132 < _lockedSync()@service.js:1415 < ()@service.js:1406 < WrappedCatch()@util.js:106 < sync()@service.js:1394", "count": 0, "author": "jeff@jeffvier.com", "creator": "jeff@jeffvier.com", "is_private": false, "creation_time": "2011-10-11T00:05:21Z", "id": 5773242, "bug_id": 693494, "raw_text": "So, when I forget to connect my SSH tunnels and, thus, cannot proxy out I get a generic grey error bar about unable to connect with Sync.  When this happens, no logs are created at all, however once I *do* connect (either by disabling my proxy or connecting the SSH tunnels) lines like the following show up in the logs after a successful Sync.  So...that's buffering somewhere which might be a bad thing (how much buffer is allocated to junk like that?) and why isn't it logging *when* it's happening?\n\nExample log lines:\n1318269622886   Sync.Service       INFO   Starting sync at 2011-10-10 11:00:22\n1318269622898   Sync.SyncScheduler DEBUG    Clearing sync triggers.\n1318269622899   Sync.Service       INFO   In sync().\n1318269623231   Sync.Service       DEBUG  Exception: NS_ERROR_PROXY_CONNECTION_REFUSED JS Stack trace: Res_get()@resource.js:473 < _fetchInfo(...)@service.js:661 < ()@service.js:1451 < WrappedNotify()@util.js:164 < WrappedLock()@util.js:132 < _lockedSync()@service.js:1415 < ()@service.js:1406 < WrappedCatch()@util.js:106 < sync()@service.js:1394", "attachment_id": null, "time": "2011-10-11T00:05:21Z", "tags": []}, {"creation_time": "2011-10-11T00:30:13Z", "is_private": false, "creator": "bugzilla@twinql.com", "tags": [], "attachment_id": null, "bug_id": 693494, "id": 5773295, "count": 1, "text": "This reminds me of Bug 625820.\n\nWe're not logging on muffled errors. Filing.", "author": "bugzilla@twinql.com", "time": "2011-10-11T00:30:13Z", "raw_text": "This reminds me of Bug 625820.\n\nWe're not logging on muffled errors. Filing."}, {"tags": [], "time": "2011-10-11T00:33:18Z", "attachment_id": null, "raw_text": "See Bug 693505.", "bug_id": 693494, "id": 5773306, "is_private": false, "creation_time": "2011-10-11T00:33:18Z", "creator": "bugzilla@twinql.com", "author": "bugzilla@twinql.com", "count": 2, "text": "See Bug 693505."}]}}}