{"bugs": {"1636589": {"comments": [{"creator": "gmierz2@outlook.com", "creation_time": "2020-05-08T21:10:14Z", "time": "2020-05-08T21:10:14Z", "count": 0, "tags": [], "id": 14805584, "author": "gmierz2@outlook.com", "raw_text": "There are some failures caused by some geckodriver artifact changes that haven't yet been fixed in the fenix repo: https://treeherder.mozilla.org/#/jobs?repo=fenix&tier=1%2C2%2C3&searchStr=btime&revision=f63cb4e09f84e09eed0c8bfccc01cf1ebf6a62ed\n\n```\nExtracting /builds/task_1588895281/fetches/browsertime.tar.bz2 to /builds/task_1588895281/fetches\nhttps://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/BwoWT4lLRyu34vdlwsJe8Q/artifacts/public/ffmpeg-4.1.4-i686-static.tar.xz resolved to 16633296 bytes with sha256 f7a2f0f8f91506d67f80fbe5b8a5c264d0fb60cb3cd258d03344890fbd55e6fd in 5.756s\nExtracting /builds/task_1588895281/fetches/ffmpeg-4.1.4-i686-static.tar.xz to /builds/task_1588895281/fetches\n/builds/task_1588895281/fetches/node.tar.xz extracted in 1.822s\nRemoving /builds/task_1588895281/fetches/node.tar.xz\n/builds/task_1588895281/fetches/ffmpeg-4.1.4-i686-static.tar.xz extracted in 1.527s\nRemoving /builds/task_1588895281/fetches/ffmpeg-4.1.4-i686-static.tar.xz\n/builds/task_1588895281/fetches/browsertime.tar.bz2 extracted in 2.309s\nRemoving /builds/task_1588895281/fetches/browsertime.tar.bz2\nattempt 2/5\nDownloading https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/KjXSn7nYTr2apHk6ax2q6A/artifacts/public/build/geckodriver.tar.xz to /builds/task_1588895281/fetches/geckodriver.tar.xz\nDownloading https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/KjXSn7nYTr2apHk6ax2q6A/artifacts/public/build/geckodriver.tar.xz\nDownload failed: HTTP Error 404: Not Found\nsleeping for 90.00s (attempt 2/5)\nattempt 3/5\nDownloading https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/KjXSn7nYTr2apHk6ax2q6A/artifacts/public/build/geckodriver.tar.xz to /builds/task_1588895281/fetches/geckodriver.tar.xz\nDownloading https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/KjXSn7nYTr2apHk6ax2q6A/artifacts/public/build/geckodriver.tar.xz\nDownload failed: HTTP Error 404: Not Found\nsleeping for 135.00s (attempt 3/5)\nattempt 4/5\nDownloading https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/KjXSn7nYTr2apHk6ax2q6A/artifacts/public/build/geckodriver.tar.xz to /builds/task_1588895281/fetches/geckodriver.tar.xz\nDownloading https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/KjXSn7nYTr2apHk6ax2q6A/artifacts/public/build/geckodriver.tar.xz\nDownload failed: HTTP Error 404: Not Found\nsleeping for 203.50s (attempt 4/5)\nattempt 5/5\nDownloading https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/KjXSn7nYTr2apHk6ax2q6A/artifacts/public/build/geckodriver.tar.xz to /builds/task_1588895281/fetches/geckodriver.tar.xz\nDownloading https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/KjXSn7nYTr2apHk6ax2q6A/artifacts/public/build/geckodriver.tar.xz\nDownload failed: HTTP Error 404: Not Found\nTraceback (most recent call last):\n  File \"./fetch-content\", line 675, in <module>\n    sys.exit(main())\n  File \"./fetch-content\", line 671, in main\n    return args.func(args)\n  File \"./fetch-content\", line 605, in command_task_artifacts\n    fetch_urls(downloads)\n  File \"./fetch-content\", line 477, in fetch_urls\n    f.result()\n  File \"/usr/lib/python3.6/concurrent/futures/_base.py\", line 432, in result\n    return self.__get_result()\n  File \"/usr/lib/python3.6/concurrent/futures/_base.py\", line 384, in __get_result\n    raise self._exception\n  File \"/usr/lib/python3.6/concurrent/futures/thread.py\", line 56, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File \"./fetch-content\", line 456, in fetch_and_extract\n    download_to_path(url, dest_path, sha256=sha256, size=size)\n  File \"./fetch-content\", line 236, in download_to_path\n    raise Exception(\"Download failed, no more retries!\")\nException: Download failed, no more retries!\n[fetches 2020-05-08T01:20:55.164Z] removing /builds/task_1588895281/fetches\n[fetches 2020-05-08T01:20:55.391Z] finished\nTraceback (most recent call last):\n  File \"./run-task\", line 1006, in <module>\n    sys.exit(main(sys.argv[1:]))\n  File \"./run-task\", line 994, in main\n    fetch_artifacts()\n  File \"./run-task\", line 653, in fetch_artifacts\n    subprocess.run(cmd, check=True, env=os.environ)\n  File \"/usr/lib/python3.6/subprocess.py\", line 438, in run\n    output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command '['/usr/bin/python3', '-u', './fetch-content', 'task-artifacts']' returned non-zero exit status 1.\n```", "text": "There are some failures caused by some geckodriver artifact changes that haven't yet been fixed in the fenix repo: https://treeherder.mozilla.org/#/jobs?repo=fenix&tier=1%2C2%2C3&searchStr=btime&revision=f63cb4e09f84e09eed0c8bfccc01cf1ebf6a62ed\n\n```\nExtracting /builds/task_1588895281/fetches/browsertime.tar.bz2 to /builds/task_1588895281/fetches\nhttps://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/BwoWT4lLRyu34vdlwsJe8Q/artifacts/public/ffmpeg-4.1.4-i686-static.tar.xz resolved to 16633296 bytes with sha256 f7a2f0f8f91506d67f80fbe5b8a5c264d0fb60cb3cd258d03344890fbd55e6fd in 5.756s\nExtracting /builds/task_1588895281/fetches/ffmpeg-4.1.4-i686-static.tar.xz to /builds/task_1588895281/fetches\n/builds/task_1588895281/fetches/node.tar.xz extracted in 1.822s\nRemoving /builds/task_1588895281/fetches/node.tar.xz\n/builds/task_1588895281/fetches/ffmpeg-4.1.4-i686-static.tar.xz extracted in 1.527s\nRemoving /builds/task_1588895281/fetches/ffmpeg-4.1.4-i686-static.tar.xz\n/builds/task_1588895281/fetches/browsertime.tar.bz2 extracted in 2.309s\nRemoving /builds/task_1588895281/fetches/browsertime.tar.bz2\nattempt 2/5\nDownloading https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/KjXSn7nYTr2apHk6ax2q6A/artifacts/public/build/geckodriver.tar.xz to /builds/task_1588895281/fetches/geckodriver.tar.xz\nDownloading https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/KjXSn7nYTr2apHk6ax2q6A/artifacts/public/build/geckodriver.tar.xz\nDownload failed: HTTP Error 404: Not Found\nsleeping for 90.00s (attempt 2/5)\nattempt 3/5\nDownloading https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/KjXSn7nYTr2apHk6ax2q6A/artifacts/public/build/geckodriver.tar.xz to /builds/task_1588895281/fetches/geckodriver.tar.xz\nDownloading https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/KjXSn7nYTr2apHk6ax2q6A/artifacts/public/build/geckodriver.tar.xz\nDownload failed: HTTP Error 404: Not Found\nsleeping for 135.00s (attempt 3/5)\nattempt 4/5\nDownloading https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/KjXSn7nYTr2apHk6ax2q6A/artifacts/public/build/geckodriver.tar.xz to /builds/task_1588895281/fetches/geckodriver.tar.xz\nDownloading https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/KjXSn7nYTr2apHk6ax2q6A/artifacts/public/build/geckodriver.tar.xz\nDownload failed: HTTP Error 404: Not Found\nsleeping for 203.50s (attempt 4/5)\nattempt 5/5\nDownloading https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/KjXSn7nYTr2apHk6ax2q6A/artifacts/public/build/geckodriver.tar.xz to /builds/task_1588895281/fetches/geckodriver.tar.xz\nDownloading https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/KjXSn7nYTr2apHk6ax2q6A/artifacts/public/build/geckodriver.tar.xz\nDownload failed: HTTP Error 404: Not Found\nTraceback (most recent call last):\n  File \"./fetch-content\", line 675, in <module>\n    sys.exit(main())\n  File \"./fetch-content\", line 671, in main\n    return args.func(args)\n  File \"./fetch-content\", line 605, in command_task_artifacts\n    fetch_urls(downloads)\n  File \"./fetch-content\", line 477, in fetch_urls\n    f.result()\n  File \"/usr/lib/python3.6/concurrent/futures/_base.py\", line 432, in result\n    return self.__get_result()\n  File \"/usr/lib/python3.6/concurrent/futures/_base.py\", line 384, in __get_result\n    raise self._exception\n  File \"/usr/lib/python3.6/concurrent/futures/thread.py\", line 56, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File \"./fetch-content\", line 456, in fetch_and_extract\n    download_to_path(url, dest_path, sha256=sha256, size=size)\n  File \"./fetch-content\", line 236, in download_to_path\n    raise Exception(\"Download failed, no more retries!\")\nException: Download failed, no more retries!\n[fetches 2020-05-08T01:20:55.164Z] removing /builds/task_1588895281/fetches\n[fetches 2020-05-08T01:20:55.391Z] finished\nTraceback (most recent call last):\n  File \"./run-task\", line 1006, in <module>\n    sys.exit(main(sys.argv[1:]))\n  File \"./run-task\", line 994, in main\n    fetch_artifacts()\n  File \"./run-task\", line 653, in fetch_artifacts\n    subprocess.run(cmd, check=True, env=os.environ)\n  File \"/usr/lib/python3.6/subprocess.py\", line 438, in run\n    output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command '['/usr/bin/python3', '-u', './fetch-content', 'task-artifacts']' returned non-zero exit status 1.\n```", "is_private": false, "attachment_id": null, "bug_id": 1636589}, {"text": "This possibly regressed by bug 1577110 given that we weren't aware of the Fenix repository. Sorry for that.\n\nAs a quick fix simply use the `tar.gz` file extension instead of `xz`. Note that we also index the signed binaries now:\n\nhttps://firefox-ci-tc.services.mozilla.com/tasks/index/gecko.v2.mozilla-central.latest.geckodriver", "raw_text": "This possibly regressed by bug 1577110 given that we weren't aware of the Fenix repository. Sorry for that.\n\nAs a quick fix simply use the `tar.gz` file extension instead of `xz`. Note that we also index the signed binaries now:\n\nhttps://firefox-ci-tc.services.mozilla.com/tasks/index/gecko.v2.mozilla-central.latest.geckodriver", "is_private": false, "creator": "hskupin@gmail.com", "creation_time": "2020-05-11T08:51:25Z", "author": "hskupin@gmail.com", "id": 14808927, "bug_id": 1636589, "count": 1, "tags": [], "time": "2020-05-11T08:51:25Z", "attachment_id": null}, {"is_private": false, "raw_text": "Thanks, I've got a patch up here: https://github.com/mozilla-mobile/fenix/pull/10558", "text": "Thanks, I've got a patch up here: https://github.com/mozilla-mobile/fenix/pull/10558", "creation_time": "2020-05-11T14:23:08Z", "author": "gmierz2@outlook.com", "id": 14809572, "creator": "gmierz2@outlook.com", "tags": [], "bug_id": 1636589, "count": 2, "time": "2020-05-11T14:23:08Z", "attachment_id": null}, {"attachment_id": null, "bug_id": 1636589, "author": "gmierz2@outlook.com", "id": 14809962, "raw_text": "PR landed - it tested browsertime in it and everything's good now.", "text": "PR landed - it tested browsertime in it and everything's good now.", "is_private": false, "time": "2020-05-11T16:23:55Z", "count": 3, "tags": [], "creator": "gmierz2@outlook.com", "creation_time": "2020-05-11T16:23:55Z"}]}}, "comments": {}}