{"bugs": {"1639955": {"comments": [{"tags": [], "bug_id": 1639955, "count": 0, "is_private": false, "author": "gmierz2@outlook.com", "time": "2020-05-21T18:48:10Z", "raw_text": "Failure in Fenix, the geckodriver path changed again...\n```\nRemoving /builds/task_1590080588/fetches/browsertime.tar.bz2\nhttps://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/OGsfn5JTTmuPnkAoITV6Qw/artifacts/public/ffmpeg-4.1.4-i686-static.tar.xz resolved to 16633296 bytes with sha256 f7a2f0f8f91506d67f80fbe5b8a5c264d0fb60cb3cd258d03344890fbd55e6fd in 4.481s\nExtracting /builds/task_1590080588/fetches/ffmpeg-4.1.4-i686-static.tar.xz to /builds/task_1590080588/fetches\nhttps://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/d8NbOplyTQubsa-WdF8ugg/artifacts/public/build/node.tar.xz resolved to 14185872 bytes with sha256 649362969c6bc729967e5ca1570432a20932be6792e99f5b5559267baefa2295 in 3.248s\nExtracting /builds/task_1590080588/fetches/node.tar.xz to /builds/task_1590080588/fetches\n/builds/task_1590080588/fetches/ffmpeg-4.1.4-i686-static.tar.xz extracted in 1.371s\nRemoving /builds/task_1590080588/fetches/ffmpeg-4.1.4-i686-static.tar.xz\n/builds/task_1590080588/fetches/node.tar.xz extracted in 1.128s\nRemoving /builds/task_1590080588/fetches/node.tar.xz\nattempt 2/5\nDownloading https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/Utfw7DA9SVGCeeqfUM6rRQ/artifacts/public/build/geckodriver.tar.gz to /builds/task_1590080588/fetches/geckodriver.tar.gz\nDownloading https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/Utfw7DA9SVGCeeqfUM6rRQ/artifacts/public/build/geckodriver.tar.gz\nDownload failed: HTTP Error 404: Not Found\nsleeping for 90.00s (attempt 2/5)\nattempt 3/5\nDownloading https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/Utfw7DA9SVGCeeqfUM6rRQ/artifacts/public/build/geckodriver.tar.gz to /builds/task_1590080588/fetches/geckodriver.tar.gz\nDownloading https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/Utfw7DA9SVGCeeqfUM6rRQ/artifacts/public/build/geckodriver.tar.gz\nDownload failed: HTTP Error 404: Not Found\nsleeping for 136.00s (attempt 3/5)\nattempt 4/5\nDownloading https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/Utfw7DA9SVGCeeqfUM6rRQ/artifacts/public/build/geckodriver.tar.gz to /builds/task_1590080588/fetches/geckodriver.tar.gz\nDownloading https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/Utfw7DA9SVGCeeqfUM6rRQ/artifacts/public/build/geckodriver.tar.gz\nDownload failed: HTTP Error 404: Not Found\nsleeping for 201.50s (attempt 4/5)\nattempt 5/5\nDownloading https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/Utfw7DA9SVGCeeqfUM6rRQ/artifacts/public/build/geckodriver.tar.gz to /builds/task_1590080588/fetches/geckodriver.tar.gz\nDownloading https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/Utfw7DA9SVGCeeqfUM6rRQ/artifacts/public/build/geckodriver.tar.gz\nDownload failed: HTTP Error 404: Not Found\nTraceback (most recent call last):\n  File \"./fetch-content\", line 675, in <module>\n    sys.exit(main())\n  File \"./fetch-content\", line 671, in main\n    return args.func(args)\n  File \"./fetch-content\", line 605, in command_task_artifacts\n    fetch_urls(downloads)\n  File \"./fetch-content\", line 477, in fetch_urls\n    f.result()\n  File \"/usr/lib/python3.6/concurrent/futures/_base.py\", line 432, in result\n    return self.__get_result()\n  File \"/usr/lib/python3.6/concurrent/futures/_base.py\", line 384, in __get_result\n    raise self._exception\n  File \"/usr/lib/python3.6/concurrent/futures/thread.py\", line 56, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File \"./fetch-content\", line 456, in fetch_and_extract\n    download_to_path(url, dest_path, sha256=sha256, size=size)\n  File \"./fetch-content\", line 236, in download_to_path\n    raise Exception(\"Download failed, no more retries!\")\nException: Download failed, no more retries!\n[fetches 2020-05-21T18:22:17.750Z] removing /builds/task_1590080588/fetches\n[fetches 2020-05-21T18:22:17.968Z] finished\nTraceback (most recent call last):\n  File \"./run-task\", line 1006, in <module>\n    sys.exit(main(sys.argv[1:]))\n  File \"./run-task\", line 994, in main\n    fetch_artifacts()\n  File \"./run-task\", line 653, in fetch_artifacts\n    subprocess.run(cmd, check=True, env=os.environ)\n  File \"/usr/lib/python3.6/subprocess.py\", line 438, in run\n    output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command '['/usr/bin/python3', '-u', './fetch-content', 'task-artifacts']' returned non-zero exit status 1.\n```", "id": 14836090, "text": "Failure in Fenix, the geckodriver path changed again...\n```\nRemoving /builds/task_1590080588/fetches/browsertime.tar.bz2\nhttps://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/OGsfn5JTTmuPnkAoITV6Qw/artifacts/public/ffmpeg-4.1.4-i686-static.tar.xz resolved to 16633296 bytes with sha256 f7a2f0f8f91506d67f80fbe5b8a5c264d0fb60cb3cd258d03344890fbd55e6fd in 4.481s\nExtracting /builds/task_1590080588/fetches/ffmpeg-4.1.4-i686-static.tar.xz to /builds/task_1590080588/fetches\nhttps://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/d8NbOplyTQubsa-WdF8ugg/artifacts/public/build/node.tar.xz resolved to 14185872 bytes with sha256 649362969c6bc729967e5ca1570432a20932be6792e99f5b5559267baefa2295 in 3.248s\nExtracting /builds/task_1590080588/fetches/node.tar.xz to /builds/task_1590080588/fetches\n/builds/task_1590080588/fetches/ffmpeg-4.1.4-i686-static.tar.xz extracted in 1.371s\nRemoving /builds/task_1590080588/fetches/ffmpeg-4.1.4-i686-static.tar.xz\n/builds/task_1590080588/fetches/node.tar.xz extracted in 1.128s\nRemoving /builds/task_1590080588/fetches/node.tar.xz\nattempt 2/5\nDownloading https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/Utfw7DA9SVGCeeqfUM6rRQ/artifacts/public/build/geckodriver.tar.gz to /builds/task_1590080588/fetches/geckodriver.tar.gz\nDownloading https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/Utfw7DA9SVGCeeqfUM6rRQ/artifacts/public/build/geckodriver.tar.gz\nDownload failed: HTTP Error 404: Not Found\nsleeping for 90.00s (attempt 2/5)\nattempt 3/5\nDownloading https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/Utfw7DA9SVGCeeqfUM6rRQ/artifacts/public/build/geckodriver.tar.gz to /builds/task_1590080588/fetches/geckodriver.tar.gz\nDownloading https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/Utfw7DA9SVGCeeqfUM6rRQ/artifacts/public/build/geckodriver.tar.gz\nDownload failed: HTTP Error 404: Not Found\nsleeping for 136.00s (attempt 3/5)\nattempt 4/5\nDownloading https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/Utfw7DA9SVGCeeqfUM6rRQ/artifacts/public/build/geckodriver.tar.gz to /builds/task_1590080588/fetches/geckodriver.tar.gz\nDownloading https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/Utfw7DA9SVGCeeqfUM6rRQ/artifacts/public/build/geckodriver.tar.gz\nDownload failed: HTTP Error 404: Not Found\nsleeping for 201.50s (attempt 4/5)\nattempt 5/5\nDownloading https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/Utfw7DA9SVGCeeqfUM6rRQ/artifacts/public/build/geckodriver.tar.gz to /builds/task_1590080588/fetches/geckodriver.tar.gz\nDownloading https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/Utfw7DA9SVGCeeqfUM6rRQ/artifacts/public/build/geckodriver.tar.gz\nDownload failed: HTTP Error 404: Not Found\nTraceback (most recent call last):\n  File \"./fetch-content\", line 675, in <module>\n    sys.exit(main())\n  File \"./fetch-content\", line 671, in main\n    return args.func(args)\n  File \"./fetch-content\", line 605, in command_task_artifacts\n    fetch_urls(downloads)\n  File \"./fetch-content\", line 477, in fetch_urls\n    f.result()\n  File \"/usr/lib/python3.6/concurrent/futures/_base.py\", line 432, in result\n    return self.__get_result()\n  File \"/usr/lib/python3.6/concurrent/futures/_base.py\", line 384, in __get_result\n    raise self._exception\n  File \"/usr/lib/python3.6/concurrent/futures/thread.py\", line 56, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File \"./fetch-content\", line 456, in fetch_and_extract\n    download_to_path(url, dest_path, sha256=sha256, size=size)\n  File \"./fetch-content\", line 236, in download_to_path\n    raise Exception(\"Download failed, no more retries!\")\nException: Download failed, no more retries!\n[fetches 2020-05-21T18:22:17.750Z] removing /builds/task_1590080588/fetches\n[fetches 2020-05-21T18:22:17.968Z] finished\nTraceback (most recent call last):\n  File \"./run-task\", line 1006, in <module>\n    sys.exit(main(sys.argv[1:]))\n  File \"./run-task\", line 994, in main\n    fetch_artifacts()\n  File \"./run-task\", line 653, in fetch_artifacts\n    subprocess.run(cmd, check=True, env=os.environ)\n  File \"/usr/lib/python3.6/subprocess.py\", line 438, in run\n    output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command '['/usr/bin/python3', '-u', './fetch-content', 'task-artifacts']' returned non-zero exit status 1.\n```", "creator": "gmierz2@outlook.com", "attachment_id": null, "creation_time": "2020-05-21T18:48:10Z"}, {"id": 14836110, "text": "Hm, could this be a regression from https://hg.mozilla.org/integration/autoland/rev/72f6e2d07667?", "creator": "hskupin@gmail.com", "attachment_id": null, "creation_time": "2020-05-21T18:57:38Z", "is_private": false, "count": 1, "bug_id": 1639955, "tags": [], "author": "hskupin@gmail.com", "time": "2020-05-21T18:57:38Z", "raw_text": "Hm, could this be a regression from https://hg.mozilla.org/integration/autoland/rev/72f6e2d07667?"}, {"creator": "gmierz2@outlook.com", "attachment_id": null, "creation_time": "2020-05-21T19:19:09Z", "id": 14836174, "text": "PR with a possible fix: https://github.com/mozilla-mobile/fenix/pull/10833", "time": "2020-05-21T19:19:09Z", "raw_text": "PR with a possible fix: https://github.com/mozilla-mobile/fenix/pull/10833", "bug_id": 1639955, "tags": [], "is_private": false, "count": 2, "author": "gmierz2@outlook.com"}, {"creation_time": "2020-05-21T19:28:33Z", "raw_text": "I had another look and it's indeed the change from `public/build` to `public/`. Until now I never got a reply from Tom, why that was necessary. Let me ask that on the other bug. And I think that this patch was wrong, because builds have to exist under `public/build`.", "creator": "hskupin@gmail.com", "attachment_id": null, "time": "2020-05-21T19:28:33Z", "author": "hskupin@gmail.com", "id": 14836189, "text": "I had another look and it's indeed the change from `public/build` to `public/`. Until now I never got a reply from Tom, why that was necessary. Let me ask that on the other bug. And I think that this patch was wrong, because builds have to exist under `public/build`.", "count": 3, "is_private": false, "tags": [], "bug_id": 1639955}, {"time": "2020-05-21T19:33:45Z", "raw_text": "Ah ok thanks, if this could be fixed on the mozilla-central side that would be ideal", "tags": [], "bug_id": 1639955, "count": 4, "is_private": false, "author": "gmierz2@outlook.com", "creator": "gmierz2@outlook.com", "attachment_id": null, "creation_time": "2020-05-21T19:33:45Z", "text": "Ah ok thanks, if this could be fixed on the mozilla-central side that would be ideal", "id": 14836202}, {"attachment_id": 9150911, "creator": "mozilla@hocat.ca", "creation_time": "2020-05-21T23:00:35Z", "id": 14836673, "text": "Created attachment 9150911\nBug 1639955: Use  prefix for geckodriver toolchain artifacts; r?aki\n\nWe originally switched it to use just `public/` becuase iscript broke with the\nextra path, but that broke out-of-tree consumers. Now that iscript is fixed,\nswitch it back.", "time": "2020-05-21T23:00:35Z", "raw_text": "We originally switched it to use just `public/` becuase iscript broke with the\nextra path, but that broke out-of-tree consumers. Now that iscript is fixed,\nswitch it back.", "is_private": false, "count": 5, "bug_id": 1639955, "tags": [], "author": "mozilla@hocat.ca"}, {"is_private": false, "count": 6, "bug_id": 1639955, "tags": [], "author": "mozilla@hocat.ca", "time": "2020-05-21T23:00:44Z", "raw_text": "", "text": "Created attachment 9150912\nBug 1639955: Include `toolchain-artifact` in the cached-task digest; r?aki", "id": 14836674, "creator": "mozilla@hocat.ca", "attachment_id": 9150912, "creation_time": "2020-05-21T23:00:44Z"}, {"id": 14836964, "text": "Pushed by mozilla@hocat.ca:\nhttps://hg.mozilla.org/integration/autoland/rev/8b12cbd16f06\nInclude `toolchain-artifact` in the cached-task digest; r=aki\nhttps://hg.mozilla.org/integration/autoland/rev/cffc2f23fdbd\nUse  prefix for geckodriver toolchain artifacts; r=aki", "author": "pulsebot@bots.tld", "is_private": false, "count": 7, "tags": [], "bug_id": 1639955, "raw_text": "Pushed by mozilla@hocat.ca:\nhttps://hg.mozilla.org/integration/autoland/rev/8b12cbd16f06\nInclude `toolchain-artifact` in the cached-task digest; r=aki\nhttps://hg.mozilla.org/integration/autoland/rev/cffc2f23fdbd\nUse  prefix for geckodriver toolchain artifacts; r=aki", "creation_time": "2020-05-22T03:42:18Z", "creator": "pulsebot@bots.tld", "attachment_id": null, "time": "2020-05-22T03:42:18Z"}, {"text": "54 failures in 759 pushes (0.071 failures/push) were associated with this bug yesterday.\n\nRepository breakdown:\n* fenix: 54\n\nPlatform breakdown:\n* android-hw-g5-7-0-arm7-api-16: 27\n* android-hw-p2-8-0-android-aarch64: 27\n\nFor more details, see:\nhttps://treeherder.mozilla.org/intermittent-failures.html#/bugdetails?bug=1639955&startday=2020-05-21&endday=2020-05-21&tree=all", "id": 14837043, "attachment_id": null, "creator": "orangefactor@bots.tld", "creation_time": "2020-05-22T06:02:51Z", "is_private": false, "count": 8, "tags": [], "bug_id": 1639955, "author": "orangefactor@bots.tld", "time": "2020-05-22T06:02:51Z", "raw_text": "54 failures in 759 pushes (0.071 failures/push) were associated with this bug yesterday.\n\nRepository breakdown:\n* fenix: 54\n\nPlatform breakdown:\n* android-hw-g5-7-0-arm7-api-16: 27\n* android-hw-p2-8-0-android-aarch64: 27\n\nFor more details, see:\nhttps://treeherder.mozilla.org/intermittent-failures.html#/bugdetails?bug=1639955&startday=2020-05-21&endday=2020-05-21&tree=all"}, {"author": "abutkovits@mozilla.com", "bug_id": 1639955, "tags": ["bugherder"], "count": 9, "is_private": false, "raw_text": "https://hg.mozilla.org/mozilla-central/rev/8b12cbd16f06\nhttps://hg.mozilla.org/mozilla-central/rev/cffc2f23fdbd", "time": "2020-05-22T09:52:59Z", "text": "https://hg.mozilla.org/mozilla-central/rev/8b12cbd16f06\nhttps://hg.mozilla.org/mozilla-central/rev/cffc2f23fdbd", "id": 14837302, "creation_time": "2020-05-22T09:52:59Z", "attachment_id": null, "creator": "abutkovits@mozilla.com"}, {"creator": "release-mgmt-account-bot@mozilla.tld", "attachment_id": null, "creation_time": "2020-05-22T12:14:47Z", "text": "Set release status flags based on info from the regressing bug 1577110", "id": 14837447, "time": "2020-05-22T12:14:47Z", "raw_text": "Set release status flags based on info from the regressing bug 1577110", "is_private": false, "count": 10, "bug_id": 1639955, "tags": [], "author": "release-mgmt-account-bot@mozilla.tld"}, {"author": "orangefactor@bots.tld", "tags": [], "bug_id": 1639955, "is_private": false, "count": 11, "raw_text": "54 failures in 4727 pushes (0.011 failures/push) were associated with this bug in the last 7 days.\n\nThis is the #20 most frequent failure this week.\n\n** This failure happened more than 30 times this week! Resolving this bug is a high priority. **\n\n** Try to resolve this bug as soon as possible. If unresolved for 2 weeks, the affected test(s) may be disabled. ** \n\nRepository breakdown:\n* fenix: 54\n\nPlatform breakdown:\n* android-hw-g5-7-0-arm7-api-16: 27\n* android-hw-p2-8-0-android-aarch64: 27\n\nFor more details, see:\nhttps://treeherder.mozilla.org/intermittent-failures.html#/bugdetails?bug=1639955&startday=2020-05-18&endday=2020-05-24&tree=all", "time": "2020-05-25T06:35:44Z", "id": 14841042, "text": "54 failures in 4727 pushes (0.011 failures/push) were associated with this bug in the last 7 days.\n\nThis is the #20 most frequent failure this week.\n\n** This failure happened more than 30 times this week! Resolving this bug is a high priority. **\n\n** Try to resolve this bug as soon as possible. If unresolved for 2 weeks, the affected test(s) may be disabled. ** \n\nRepository breakdown:\n* fenix: 54\n\nPlatform breakdown:\n* android-hw-g5-7-0-arm7-api-16: 27\n* android-hw-p2-8-0-android-aarch64: 27\n\nFor more details, see:\nhttps://treeherder.mozilla.org/intermittent-failures.html#/bugdetails?bug=1639955&startday=2020-05-18&endday=2020-05-24&tree=all", "creation_time": "2020-05-25T06:35:44Z", "creator": "orangefactor@bots.tld", "attachment_id": null}]}}, "comments": {}}