{"comments": {}, "bugs": {"1637305": {"comments": [{"creation_time": "2020-05-12T16:10:29Z", "creator": "ahal@mozilla.com", "attachment_id": null, "id": 14814526, "text": "From https://bugzilla.mozilla.org/show_bug.cgi?id=1637271#c2\n```\n$ mach try syntax -b do -p win32,win64,win32-mingwclang,win64-mingwclang,linux32,linux64 -u cppunit,mochitest -t none\n['D:\\\\mozilla-build\\\\/msys/bin/sh.exe', 'u:/mz/mozilla-central/python/mozbuild/mozbuild/mozconfig_loader', 'u:/mz/mozilla-central', 'U:/mz/mozconfig', 'd:\\\\mozilla-build\\\\python3\\\\python3.exe', 'u:/mz/mozilla-central/python/mozbuild/mozbuild/action/dump_env.py']\n('d:\\\\mozilla-build\\\\python\\\\Scripts\\\\hg.EXE', b'status', b'--modified', b'--added', b'--removed', b'--deleted')\nError running mach:\n\n    ['try', 'syntax', '-b', 'do', '-p', 'win32,win64,win32-mingwclang,win64-mingwclang,linux32,linux64', '-u', 'cppunit,mochitest', '-t', 'none']\n\nThe error occurred in code that was called by the mach command. This is either\na bug in the called code itself or in the way that mach is calling it.\nYou can invoke |./mach busted| to check if this issue is already on file. If it\nisn't, please use |./mach busted file| to report it. If |./mach busted| is\nmisbehaving, you can also inspect the dependencies of bug 1543241.\n\nIf filing a bug, please include the full output of mach, including this error\nmessage.\n\nThe details of the failure are as follows:\n\nTypeError: a bytes-like object is required, not 'str'\n\n  File \"u:\\mz\\mozilla-central\\tools/tryselect/mach_commands.py\", line 417, in try_syntax\n    return self.run(**kwargs)\n  File \"u:\\mz\\mozilla-central\\tools/tryselect/mach_commands.py\", line 178, in run\n    return mod.run(**kwargs)\n  File \"u:\\mz\\mozilla-central\\tools\\tryselect\\selectors\\syntax.py\", line 614, in run\n    return at.run(**kwargs)\n  File \"u:\\mz\\mozilla-central\\tools\\tryselect\\selectors\\syntax.py\", line 609, in run\n    closed_tree=kwargs[\"closed_tree\"])\n  File \"u:\\mz\\mozilla-central\\tools\\tryselect\\push.py\", line 144, in push_to_try\n    check_working_directory(push)\n  File \"u:\\mz\\mozilla-central\\tools\\tryselect\\push.py\", line 83, in check_working_directory\n    if not vcs.working_directory_clean():\n  File \"u:\\mz\\mozilla-central\\python/mozversioncontrol\\mozversioncontrol\\__init__.py\", line 412, in working_directory_clean\n    return not len(self._run(*args).strip())\n  File \"u:\\mz\\mozilla-central\\python/mozversioncontrol\\mozversioncontrol\\__init__.py\", line 318, in _run\n    return super(HgRepository, self)._run(*args, **runargs)\n  File \"u:\\mz\\mozilla-central\\python/mozversioncontrol\\mozversioncontrol\\__init__.py\", line 115, in _run\n    universal_newlines=True)\n  File \"d:\\mozilla-build\\python3\\lib\\subprocess.py\", line 395, in check_output\n    **kwargs).stdout\n  File \"d:\\mozilla-build\\python3\\lib\\subprocess.py\", line 475, in run\n    with Popen(*popenargs, **kwargs) as process:\n  File \"d:\\mozilla-build\\python3\\lib\\subprocess.py\", line 778, in __init__\n    restore_signals, start_new_session)\n  File \"d:\\mozilla-build\\python3\\lib\\subprocess.py\", line 1122, in _execute_child\n    args = list2cmdline(args)\n  File \"d:\\mozilla-build\\python3\\lib\\subprocess.py\", line 533, in list2cmdline\n    needquote = (\" \" in arg) or (\"\\t\" in arg) or not arg\n```\n\nI can't reproduce on WSL, so assuming this is Windows only.", "raw_text": "From https://bugzilla.mozilla.org/show_bug.cgi?id=1637271#c2\n```\n$ mach try syntax -b do -p win32,win64,win32-mingwclang,win64-mingwclang,linux32,linux64 -u cppunit,mochitest -t none\n['D:\\\\mozilla-build\\\\/msys/bin/sh.exe', 'u:/mz/mozilla-central/python/mozbuild/mozbuild/mozconfig_loader', 'u:/mz/mozilla-central', 'U:/mz/mozconfig', 'd:\\\\mozilla-build\\\\python3\\\\python3.exe', 'u:/mz/mozilla-central/python/mozbuild/mozbuild/action/dump_env.py']\n('d:\\\\mozilla-build\\\\python\\\\Scripts\\\\hg.EXE', b'status', b'--modified', b'--added', b'--removed', b'--deleted')\nError running mach:\n\n    ['try', 'syntax', '-b', 'do', '-p', 'win32,win64,win32-mingwclang,win64-mingwclang,linux32,linux64', '-u', 'cppunit,mochitest', '-t', 'none']\n\nThe error occurred in code that was called by the mach command. This is either\na bug in the called code itself or in the way that mach is calling it.\nYou can invoke |./mach busted| to check if this issue is already on file. If it\nisn't, please use |./mach busted file| to report it. If |./mach busted| is\nmisbehaving, you can also inspect the dependencies of bug 1543241.\n\nIf filing a bug, please include the full output of mach, including this error\nmessage.\n\nThe details of the failure are as follows:\n\nTypeError: a bytes-like object is required, not 'str'\n\n  File \"u:\\mz\\mozilla-central\\tools/tryselect/mach_commands.py\", line 417, in try_syntax\n    return self.run(**kwargs)\n  File \"u:\\mz\\mozilla-central\\tools/tryselect/mach_commands.py\", line 178, in run\n    return mod.run(**kwargs)\n  File \"u:\\mz\\mozilla-central\\tools\\tryselect\\selectors\\syntax.py\", line 614, in run\n    return at.run(**kwargs)\n  File \"u:\\mz\\mozilla-central\\tools\\tryselect\\selectors\\syntax.py\", line 609, in run\n    closed_tree=kwargs[\"closed_tree\"])\n  File \"u:\\mz\\mozilla-central\\tools\\tryselect\\push.py\", line 144, in push_to_try\n    check_working_directory(push)\n  File \"u:\\mz\\mozilla-central\\tools\\tryselect\\push.py\", line 83, in check_working_directory\n    if not vcs.working_directory_clean():\n  File \"u:\\mz\\mozilla-central\\python/mozversioncontrol\\mozversioncontrol\\__init__.py\", line 412, in working_directory_clean\n    return not len(self._run(*args).strip())\n  File \"u:\\mz\\mozilla-central\\python/mozversioncontrol\\mozversioncontrol\\__init__.py\", line 318, in _run\n    return super(HgRepository, self)._run(*args, **runargs)\n  File \"u:\\mz\\mozilla-central\\python/mozversioncontrol\\mozversioncontrol\\__init__.py\", line 115, in _run\n    universal_newlines=True)\n  File \"d:\\mozilla-build\\python3\\lib\\subprocess.py\", line 395, in check_output\n    **kwargs).stdout\n  File \"d:\\mozilla-build\\python3\\lib\\subprocess.py\", line 475, in run\n    with Popen(*popenargs, **kwargs) as process:\n  File \"d:\\mozilla-build\\python3\\lib\\subprocess.py\", line 778, in __init__\n    restore_signals, start_new_session)\n  File \"d:\\mozilla-build\\python3\\lib\\subprocess.py\", line 1122, in _execute_child\n    args = list2cmdline(args)\n  File \"d:\\mozilla-build\\python3\\lib\\subprocess.py\", line 533, in list2cmdline\n    needquote = (\" \" in arg) or (\"\\t\" in arg) or not arg\n```\n\nI can't reproduce on WSL, so assuming this is Windows only.", "time": "2020-05-12T16:10:29Z", "author": "ahal@mozilla.com", "count": 0, "is_private": false, "tags": [], "bug_id": 1637305}, {"tags": [], "bug_id": 1637305, "is_private": false, "count": 1, "author": "ahal@mozilla.com", "time": "2020-05-12T16:23:41Z", "raw_text": "This is a bug in mozversioncontrol. For some reason the `working_directory_clean` function explicitly uses byte-strings as its argument:\nhttps://searchfox.org/mozilla-central/source/python/mozversioncontrol/mozversioncontrol/__init__.py#402\n\nLooks like it's always been like this and we can likely just use text. Notably, the git implementation uses text, only the hg implementation uses bytes.", "id": 14814558, "text": "This is a bug in mozversioncontrol. For some reason the `working_directory_clean` function explicitly uses byte-strings as its argument:\nhttps://searchfox.org/mozilla-central/source/python/mozversioncontrol/mozversioncontrol/__init__.py#402\n\nLooks like it's always been like this and we can likely just use text. Notably, the git implementation uses text, only the hg implementation uses bytes.", "attachment_id": null, "creator": "ahal@mozilla.com", "creation_time": "2020-05-12T16:23:41Z"}, {"id": 14814571, "text": "Created attachment 9147669\nBug 1637305 - [mozversioncontrol] Don't use bytes in HGRepository.working_directory_clean, r?rstewart", "attachment_id": 9147669, "creator": "ahal@mozilla.com", "creation_time": "2020-05-12T16:30:46Z", "is_private": false, "count": 2, "tags": [], "bug_id": 1637305, "author": "ahal@mozilla.com", "time": "2020-05-12T16:30:46Z", "raw_text": ""}, {"count": 3, "is_private": false, "tags": [], "bug_id": 1637305, "author": "ahal@mozilla.com", "time": "2020-05-12T16:32:20Z", "raw_text": ":toshi, does the attached patch fix the issue for you? I'm pretty confident it will, but I wasn't able to reproduce so would like to verify.", "text": ":toshi, does the attached patch fix the issue for you? I'm pretty confident it will, but I wasn't able to reproduce so would like to verify.", "id": 14814578, "attachment_id": null, "creator": "ahal@mozilla.com", "creation_time": "2020-05-12T16:32:20Z"}, {"id": 14814609, "text": "*** Bug 1637261 has been marked as a duplicate of this bug. ***", "author": "rstewart@mozilla.com", "is_private": false, "count": 4, "tags": [], "bug_id": 1637305, "creation_time": "2020-05-12T16:41:00Z", "raw_text": "", "creator": "rstewart@mozilla.com", "attachment_id": null, "time": "2020-05-12T16:41:00Z"}, {"bug_id": 1637305, "tags": [], "is_private": false, "count": 5, "author": "tkikuchi@mozilla.com", "time": "2020-05-12T16:45:39Z", "raw_text": "(In reply to Andrew Halberstadt [:ahal] from comment #3)\n> :toshi, does the attached patch fix the issue for you? I'm pretty confident it will, but I wasn't able to reproduce so would like to verify.\n\nThank you looking into this quickly!  With D74880, I hit a different error as below.\n\n```\n$ mach try syntax -b do -p win32,win64,win32-mingwclang,win64-mingwclang,linux32,linux64 -u cppunit,mochitest -t none\n['D:\\\\mozilla-build\\\\/msys/bin/sh.exe', 'u:/mz/mozilla-central/python/mozbuild/mozbuild/mozconfig_loader', 'u:/mz/mozilla-central', 'U:/mz/mozconfig', 'd:\\\\mozilla-build\\\\python3\\\\python3.exe', 'u:/mz/mozilla-central/python/mozbuild/mozbuild/action/dump_env.py']\n('d:\\\\mozilla-build\\\\python\\\\Scripts\\\\hg.EXE', 'status', '--modified', '--added', '--removed', '--deleted')\n('d:\\\\mozilla-build\\\\python\\\\Scripts\\\\hg.EXE', 'revert', '-a')\nError running mach:\n\n    ['try', 'syntax', '-b', 'do', '-p', 'win32,win64,win32-mingwclang,win64-mingwclang,linux32,linux64', '-u', 'cppunit,mochitest', '-t', 'none']\n\nThe error occurred in code that was called by the mach command. This is either\na bug in the called code itself or in the way that mach is calling it.\nYou can invoke |./mach busted| to check if this issue is already on file. If it\nisn't, please use |./mach busted file| to report it. If |./mach busted| is\nmisbehaving, you can also inspect the dependencies of bug 1543241.\n\nIf filing a bug, please include the full output of mach, including this error\nmessage.\n\nThe details of the failure are as follows:\n\nTypeError: environment can only contain strings\n\n  File \"u:\\mz\\mozilla-central\\tools/tryselect/mach_commands.py\", line 417, in try_syntax\n    return self.run(**kwargs)\n  File \"u:\\mz\\mozilla-central\\tools/tryselect/mach_commands.py\", line 178, in run\n    return mod.run(**kwargs)\n  File \"u:\\mz\\mozilla-central\\tools\\tryselect\\selectors\\syntax.py\", line 614, in run\n    return at.run(**kwargs)\n  File \"u:\\mz\\mozilla-central\\tools\\tryselect\\selectors\\syntax.py\", line 609, in run\n    closed_tree=kwargs[\"closed_tree\"])\n  File \"u:\\mz\\mozilla-central\\tools\\tryselect\\push.py\", line 182, in push_to_try\n    vcs.push_to_try(commit_message)\n  File \"u:\\mz\\mozilla-central\\python/mozversioncontrol\\mozversioncontrol\\__init__.py\", line 427, in push_to_try\n    env=self._env)\n  File \"d:\\mozilla-build\\python3\\lib\\subprocess.py\", line 342, in check_call\n    retcode = call(*popenargs, **kwargs)\n  File \"d:\\mozilla-build\\python3\\lib\\subprocess.py\", line 323, in call\n    with Popen(*popenargs, **kwargs) as p:\n  File \"d:\\mozilla-build\\python3\\lib\\subprocess.py\", line 778, in __init__\n    restore_signals, start_new_session)\n  File \"d:\\mozilla-build\\python3\\lib\\subprocess.py\", line 1181, in _execute_child\n    startupinfo)\n```", "text": "(In reply to Andrew Halberstadt [:ahal] from comment #3)\n> :toshi, does the attached patch fix the issue for you? I'm pretty confident it will, but I wasn't able to reproduce so would like to verify.\n\nThank you looking into this quickly!  With D74880, I hit a different error as below.\n\n```\n$ mach try syntax -b do -p win32,win64,win32-mingwclang,win64-mingwclang,linux32,linux64 -u cppunit,mochitest -t none\n['D:\\\\mozilla-build\\\\/msys/bin/sh.exe', 'u:/mz/mozilla-central/python/mozbuild/mozbuild/mozconfig_loader', 'u:/mz/mozilla-central', 'U:/mz/mozconfig', 'd:\\\\mozilla-build\\\\python3\\\\python3.exe', 'u:/mz/mozilla-central/python/mozbuild/mozbuild/action/dump_env.py']\n('d:\\\\mozilla-build\\\\python\\\\Scripts\\\\hg.EXE', 'status', '--modified', '--added', '--removed', '--deleted')\n('d:\\\\mozilla-build\\\\python\\\\Scripts\\\\hg.EXE', 'revert', '-a')\nError running mach:\n\n    ['try', 'syntax', '-b', 'do', '-p', 'win32,win64,win32-mingwclang,win64-mingwclang,linux32,linux64', '-u', 'cppunit,mochitest', '-t', 'none']\n\nThe error occurred in code that was called by the mach command. This is either\na bug in the called code itself or in the way that mach is calling it.\nYou can invoke |./mach busted| to check if this issue is already on file. If it\nisn't, please use |./mach busted file| to report it. If |./mach busted| is\nmisbehaving, you can also inspect the dependencies of bug 1543241.\n\nIf filing a bug, please include the full output of mach, including this error\nmessage.\n\nThe details of the failure are as follows:\n\nTypeError: environment can only contain strings\n\n  File \"u:\\mz\\mozilla-central\\tools/tryselect/mach_commands.py\", line 417, in try_syntax\n    return self.run(**kwargs)\n  File \"u:\\mz\\mozilla-central\\tools/tryselect/mach_commands.py\", line 178, in run\n    return mod.run(**kwargs)\n  File \"u:\\mz\\mozilla-central\\tools\\tryselect\\selectors\\syntax.py\", line 614, in run\n    return at.run(**kwargs)\n  File \"u:\\mz\\mozilla-central\\tools\\tryselect\\selectors\\syntax.py\", line 609, in run\n    closed_tree=kwargs[\"closed_tree\"])\n  File \"u:\\mz\\mozilla-central\\tools\\tryselect\\push.py\", line 182, in push_to_try\n    vcs.push_to_try(commit_message)\n  File \"u:\\mz\\mozilla-central\\python/mozversioncontrol\\mozversioncontrol\\__init__.py\", line 427, in push_to_try\n    env=self._env)\n  File \"d:\\mozilla-build\\python3\\lib\\subprocess.py\", line 342, in check_call\n    retcode = call(*popenargs, **kwargs)\n  File \"d:\\mozilla-build\\python3\\lib\\subprocess.py\", line 323, in call\n    with Popen(*popenargs, **kwargs) as p:\n  File \"d:\\mozilla-build\\python3\\lib\\subprocess.py\", line 778, in __init__\n    restore_signals, start_new_session)\n  File \"d:\\mozilla-build\\python3\\lib\\subprocess.py\", line 1181, in _execute_child\n    startupinfo)\n```", "id": 14814620, "creator": "tkikuchi@mozilla.com", "attachment_id": null, "creation_time": "2020-05-12T16:45:39Z"}, {"id": 14814635, "text": "On that line of `__init__.py` you would need to call `ensure_subprocess_env(self._env)` to make sure the env only contains the correct types. I can throw a quick patch in for that.", "creator": "rstewart@mozilla.com", "attachment_id": null, "creation_time": "2020-05-12T16:49:23Z", "is_private": false, "count": 6, "bug_id": 1637305, "tags": [], "author": "rstewart@mozilla.com", "time": "2020-05-12T16:49:23Z", "raw_text": "On that line of `__init__.py` you would need to call `ensure_subprocess_env(self._env)` to make sure the env only contains the correct types. I can throw a quick patch in for that."}, {"raw_text": "(In reply to Ricky Stewart from comment #6)\n> On that line of `__init__.py` you would need to call `ensure_subprocess_env(self._env)` to make sure the env only contains the correct types. I can throw a quick patch in for that.\n\nSweet, I got 'mach try' back!!  Here's a patch I applied: https://hg.mozilla.org/try/rev/bb4571de37a2b28d6da85e15482680428d223d6e.", "time": "2020-05-12T17:01:12Z", "author": "tkikuchi@mozilla.com", "tags": [], "bug_id": 1637305, "is_private": false, "count": 7, "creation_time": "2020-05-12T17:01:12Z", "attachment_id": null, "creator": "tkikuchi@mozilla.com", "text": "(In reply to Ricky Stewart from comment #6)\n> On that line of `__init__.py` you would need to call `ensure_subprocess_env(self._env)` to make sure the env only contains the correct types. I can throw a quick patch in for that.\n\nSweet, I got 'mach try' back!!  Here's a patch I applied: https://hg.mozilla.org/try/rev/bb4571de37a2b28d6da85e15482680428d223d6e.", "id": 14814688}, {"text": "(The patch in question for reference: https://phabricator.services.mozilla.com/D74888)", "id": 14814926, "author": "rstewart@mozilla.com", "tags": [], "bug_id": 1637305, "is_private": false, "count": 8, "creation_time": "2020-05-12T17:08:19Z", "raw_text": "(The patch in question for reference: https://phabricator.services.mozilla.com/D74888)", "time": "2020-05-12T17:08:19Z", "creator": "rstewart@mozilla.com", "attachment_id": null}, {"creator": "honzab.moz@firemni.cz", "attachment_id": null, "creation_time": "2020-05-12T17:09:09Z", "id": 14814927, "text": "(In reply to Toshihito Kikuchi [:toshi] from comment #7)\n> (In reply to Ricky Stewart from comment #6)\n> > On that line of `__init__.py` you would need to call `ensure_subprocess_env(self._env)` to make sure the env only contains the correct types. I can throw a quick patch in for that.\n> \n> Sweet, I got 'mach try' back!!  Here's a patch I applied: https://hg.mozilla.org/try/rev/bb4571de37a2b28d6da85e15482680428d223d6e.\n\nConfirming a fix for me too!", "time": "2020-05-12T17:09:09Z", "raw_text": "(In reply to Toshihito Kikuchi [:toshi] from comment #7)\n> (In reply to Ricky Stewart from comment #6)\n> > On that line of `__init__.py` you would need to call `ensure_subprocess_env(self._env)` to make sure the env only contains the correct types. I can throw a quick patch in for that.\n> \n> Sweet, I got 'mach try' back!!  Here's a patch I applied: https://hg.mozilla.org/try/rev/bb4571de37a2b28d6da85e15482680428d223d6e.\n\nConfirming a fix for me too!", "is_private": false, "count": 9, "tags": [], "bug_id": 1637305, "author": "honzab.moz@firemni.cz"}, {"text": "(In reply to Honza Bambas (:mayhemer) from comment #9)\n> (In reply to Toshihito Kikuchi [:toshi] from comment #7)\n> > Sweet, I got 'mach try' back!!  Here's a patch I applied: https://hg.mozilla.org/try/rev/bb4571de37a2b28d6da85e15482680428d223d6e.\n> \n> Confirming a fix for me too!\n\nMe too!  Fixes the problems I reported in duplicate bug 1637261.  Thanks!", "id": 14814938, "creation_time": "2020-05-12T17:15:16Z", "attachment_id": null, "creator": "mozbugs@sidstamm.com", "author": "mozbugs@sidstamm.com", "bug_id": 1637305, "tags": [], "count": 10, "is_private": false, "raw_text": "(In reply to Honza Bambas (:mayhemer) from comment #9)\n> (In reply to Toshihito Kikuchi [:toshi] from comment #7)\n> > Sweet, I got 'mach try' back!!  Here's a patch I applied: https://hg.mozilla.org/try/rev/bb4571de37a2b28d6da85e15482680428d223d6e.\n> \n> Confirming a fix for me too!\n\nMe too!  Fixes the problems I reported in duplicate bug 1637261.  Thanks!", "time": "2020-05-12T17:15:16Z"}, {"is_private": false, "count": 11, "bug_id": 1637305, "tags": [], "author": "pulsebot@bots.tld", "time": "2020-05-12T18:16:30Z", "raw_text": "Pushed by ahalberstadt@mozilla.com:\nhttps://hg.mozilla.org/integration/autoland/rev/998362228c1f\n[mozversioncontrol] Don't use bytes in HGRepository.working_directory_clean, r=rstewart", "id": 14815044, "text": "Pushed by ahalberstadt@mozilla.com:\nhttps://hg.mozilla.org/integration/autoland/rev/998362228c1f\n[mozversioncontrol] Don't use bytes in HGRepository.working_directory_clean, r=rstewart", "attachment_id": null, "creator": "pulsebot@bots.tld", "creation_time": "2020-05-12T18:16:30Z"}, {"author": "pulsebot@bots.tld", "bug_id": 1637305, "tags": [], "is_private": false, "count": 12, "raw_text": "Pushed by apavel@mozilla.com:\nhttps://hg.mozilla.org/mozilla-central/rev/78ca58d04a9b\n[mozversioncontrol] Don't use bytes in HGRepository.working_directory_clean, r=rstewart a=try-push-fix", "time": "2020-05-12T21:25:31Z", "id": 14815484, "text": "Pushed by apavel@mozilla.com:\nhttps://hg.mozilla.org/mozilla-central/rev/78ca58d04a9b\n[mozversioncontrol] Don't use bytes in HGRepository.working_directory_clean, r=rstewart a=try-push-fix", "creation_time": "2020-05-12T21:25:31Z", "attachment_id": null, "creator": "pulsebot@bots.tld"}, {"count": 13, "is_private": false, "tags": ["bugherder"], "bug_id": 1637305, "author": "apavel@mozilla.com", "time": "2020-05-12T21:35:07Z", "raw_text": "https://hg.mozilla.org/mozilla-central/rev/78ca58d04a9b", "text": "https://hg.mozilla.org/mozilla-central/rev/78ca58d04a9b", "id": 14815503, "creator": "apavel@mozilla.com", "attachment_id": null, "creation_time": "2020-05-12T21:35:07Z"}, {"time": "2020-05-13T03:54:07Z", "raw_text": "https://hg.mozilla.org/mozilla-central/rev/998362228c1f", "tags": ["bugherder"], "bug_id": 1637305, "count": 14, "is_private": false, "author": "apavel@mozilla.com", "attachment_id": null, "creator": "apavel@mozilla.com", "creation_time": "2020-05-13T03:54:07Z", "id": 14815962, "text": "https://hg.mozilla.org/mozilla-central/rev/998362228c1f"}, {"id": 14816549, "text": "Set release status flags based on info from the regressing bug 1632429", "creation_time": "2020-05-13T12:19:35Z", "attachment_id": null, "creator": "release-mgmt-account-bot@mozilla.tld", "author": "release-mgmt-account-bot@mozilla.tld", "tags": [], "bug_id": 1637305, "count": 15, "is_private": false, "raw_text": "Set release status flags based on info from the regressing bug 1632429", "time": "2020-05-13T12:19:35Z"}]}}}